### ISSUE TITLE
There is a recording in the permissions during the installation of the Android version

### ISSUE THREAD

**Issue by takker0708** [Covid-19Radar/Covid19Radar#165] opened 2020-05-12 16:26 UTC
Hi,

During installation, the authentication settings include recording and reading the SD card.
If you don't need it, I think it's better to delete it.
Ignore this setting if it is for debugging.

Version is Android 5.1.1
ASUS Xenfone Go

Sincerely

**Comment by oyasan-ba2** [comment] 2020-05-16 06:33
@takker0708 Thank you for your report!. I did NOT reproduce this issue with Covid19RadarAndroid 1.0(268) on Nexus 7, Android 6.0.1. Could you try the latest version ?

**Comment by oyasan-ba2** [comment] 2020-05-22 10:52
@takker0708 I checked READ_EXTERNAL_STORAGE permission is need for Debug build and
following permissions are unnecessary for this app.
uses-permission android:name="android.permission.RECORD_AUDIO"
uses-permission android:name="android.permission.BIND_MIDI_DEVICE_SERVICE"
uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"
assembly: UsesPermission(Android.Manifest.Permission.WriteExternalStorage)

Then, I removed above by my pull request.

**Comment by takker0708** [comment] 2020-05-22 11:12
@oyasan-ba2 Thank you!
This issue is closed.

**Comment by oyasan-ba2** [comment] 2020-06-04 08:18
@changeworld Could you please close this issue because this issue was fixed in the latest master branch ?

**Closed** 2020-06-04 08:40 UTC
